name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ linux, darwin, windows ]
        arch: [ amd64, arm64 ]
        include:
          - os: linux
            ext: ""
          - os: darwin
            ext: ""
          - os: windows
            ext: .exe

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          mkdir dist
          export CGO_ENABLED=0
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          go build -ldflags="-s -w" -trimpath -o dist/sshm-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} ./cmd/sshm

      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          file: dist/sshm-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          output-file: sbom/sshm-${{ matrix.os }}-${{ matrix.arch }}-sbom.cyclonedx.json
          format: cyclonedx-json
          upload-artifact: false
          upload-release-assets: false

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: dist/*
          sbom-path: sbom/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: sshm-${{ matrix.os }}-${{ matrix.arch }}
          path: |
              dist/
              sbom/

  release:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bump tag
        id: bump_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          files: dist/**
          name: ${{ steps.bump_tag.outputs.new_tag }}
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
